version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: advisor-db
      #env variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advisor_finder
       #port mapping
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data

    healthcheck:
      test:["CMD-SHELL", "pg_ready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  backendL
    build: ./backend
    container_name: advisor-backend
    
    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/advisor_finder
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./backend:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
