version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: advisor-db
      #env variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advisor_finder
       #port mapping
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data

    healthcheck:
      test:["CMD-SHELL", "pg_ready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
